apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  # Values are base64 encoded
  # "calculator-user"
  MONGO_USERNAME: Y2FsY3VsYXRvci11c2Vy
  # "calculator-password"
  MONGO_PASSWORD: Y2FsY3VsYXRvci1wYXNzd29yZA==